---
- hosts: ws
  become: true
  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start the httpd daemon
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create a file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Add content to a file
      lineinfile:
      path: /var/www/html/index.html
      line: "<h1>This was done using Ansible</h1>"   
