---
- hosts: ws
  become: true
  vars:
    httpd_content: "<h1>It was good seeing us after many years</h1>"
  tasks:
    - name: Update all packages
      package:
        name: "*"
        state: latest

    - name: Install Apache
      yum:
        name: httpd
        state: latest

    - name: Start the httpd daemon
      service:
        name: httpd
        state: started
        enabled: true

    - name: Create a file
      file:
        path: /var/www/html/index.html
        state: touch

    - name: Overwrite content in the file
      lineinfile:
        path: /var/www/html/index.html
        line: "{{ httpd_content }}"
        regexp: '<h1>.*</h1>'  # This matches any existing <h1> content
        state: present
      notify: Restart Daemon

  handlers:
    - name: Restart Daemon
      service:
        name: httpd
        state: restarted

